workflows:
  build-android-apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        PACKAGE_NAME: "com.wanlegacy.reset30"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - wanlegacyapps@gmail.com
